### ISSUE TITLE
Auto emoji not working

### ISSUE THREAD

**Issue by tomho69** [Maikels/slack#2]
!emojis add indiër :flag-in: 

indiër werkt dan niet, noch indier. 
Wrs regex error, nicom zou alvast geen clue hebben how to fix.

Please no xumpy code.

**Comment by Maikels** [comment]
Regex aangepast naar :
[^a-zA-Z0-9'ëäöüÄÖÜßéÉèÈêÊ ]

Geen xumpy code dus.
